from __future__ import annotations

"""
Service Registry - Canonical promotional messages for services.

This registry provides the single source of truth for service-first replies.
When a user asks about any service, the system returns the full canonical message.
"""

SERVICE_REGISTRY: dict[str, dict[str, dict[str, list[str]] | list[str]]] = {
    "laser_hair_removal_full_body": {
        "aliases": [
            "laser",
            "laser hair removal",
            "full body laser",
            "diode laser",
            "do you do laser",
            "laser price",
            "laser booking",
            "laser hair",
            "hair removal",
            "full body",
            "can i come for laser",
            "i want to book laser",
            "laser appt", "laser appointment", "laser session", "laser sesh",
            "laser hair", "laser removal", "laser remove hair", "get laser",
            "do u do laser", "do you guys do laser", "do yall do laser",
            "are you doing laser", "can i do laser", "can i get laser",
            "i need laser", "i wanna do laser", "i want laser", "i wanna book laser",
            "book laser", "schedule laser", "set up laser", "can i schedule laser",
            "how much is laser", "how much for laser", "laser cost", "laser costs",
            "laser prices", "price for laser", "pricing for laser", "rate for laser",
          
            "full body", "whole body", "entire body", "head to toe", "all over",
            "full body laser", "laser full body", "whole body laser", "laser for full body",
            "fullbody", "full-body", "full body package", "full body deal",
          
            "diode", "diode laser", "diode hair removal", "diode full body",
            "diode laser hair removal", "diod", "diodee",
          
            "legs and arms", "underarms and legs", "bikini and underarms",
            "everything", "all areas", "all parts",
          
            "how many sessions", "how many times", "how many visits",
            "how many do i need", "how many treatments", "how many appointments",
            "how long is the process", "how long does it take",
            "do i need multiple sessions", "is it like 6 sessions",
          
            "lazer", "lazer hair removal", "lazer full body", "lazor", "lasr",
            "laser har removal", "laser hair remvoal", "hairremoval",
          
            "laser✨", "laser 🤍", "laser pls", "laser please", "laser??",
          ],
        "message": {
            "en": [
                "🌸LIMITED TIME PROMO",
                "",
                "Full Body Diode Laser Hair Removal",
                "• Full Body – only $150 per session",
                "• Add Full Face – 50% OFF – $50",
                "",
                "✨Safe & effective for all skin types",
                "✨Long-term hair reduction",
                "✨Minimal discomfort",
                "",
                "🌸SPECIAL BONUS:",
                "",
                "If you complete all 6 sessions consecutively you will keep the promo price.",
            ],
            "es": [
                "🌸PROMO POR TIEMPO LIMITADO",
                "",
                "Depilación Láser Diodo Cuerpo Completo",
                "• Cuerpo Completo – solo $150 por sesión",
                "• Agregar Rostro Completo – 50% DESCUENTO – $50",
                "",
                "✨Seguro y efectivo para todos los tipos de piel",
                "✨Reducción de vello a largo plazo",
                "✨Mínima molestia",
                "",
                "🌸BONO ESPECIAL:",
                "",
                "Si completas las 6 sesiones consecutivamente, mantendrás el precio promocional.",
            ],
        },
    },
    "facial_deep_blackhead_removal": {
        "aliases": [
            "facial",
            "blackhead",
            "blackhead removal",
            "deep facial",
            "facial price",
            "facial treatment",
            "do you do facial",
            "can i get facial",
            "clean pores",
            "cleanse pores",
            "pore cleansing",
            "pore cleaning",
            "can i clean pores",
            "do you cleanse pores",
            "do you clean pores",
            "pore treatment",
            "pore extraction",
            "deep pore cleansing",
            "exfoliate",
            "exfoliation",
            "skin exfoliation",
            "deep clean",
            "deep cleaning",
            "deep cleanse",
            "deep cleansing facial",
            "clean my face",
            "clean my skin",
            "skin cleaning",
            "skin deep clean",
            "face deep clean",
            "face cleaning",
            "dirty pores",
            "clogged pores",
            "clogged skin",
            "black stuff in pores",
            "pores are dirty",
            "my pores are clogged",
            "pore extraction",
            "pore extraction facial",
            "pore extraction treatment",
            "pore extraction service",
        ],
        "message": {
            "en": [
                "💆LIMITED TIME PROMO",
                "",
                "Facial + Deep Blackhead Removal $120–$150 (price varies depending on skin concerns and treatment needs)",
                "",
                "✨Deep cleansing",
                "✨Blackhead removal",
                "✨Gentle exfoliation",
                "✨Calming mask",
                "✨Ultrasonic Skin Treatment",
                "✨Hydration + SPF finish",
                "",
                "This treatment is customized based on your skin to ensure the best results possible.",
            ],
            "es": [
                "💆PROMO POR TIEMPO LIMITADO",
                "",
                "Facial + Extracción Profunda de Puntos Negros $120–$150 (el precio varía según las preocupaciones de la piel y las necesidades del tratamiento)",
                "",
                "✨Limpieza profunda",
                "✨Extracción de puntos negros",
                "✨Exfoliación suave",
                "✨Mascarilla calmante",
                "✨Tratamiento Ultrasonido de Piel",
                "✨Hidratación + SPF final",
                "",
                "Este tratamiento se personaliza según tu piel para garantizar los mejores resultados posibles.",
            ],
        },
    },
    "brow_combo": {
        "aliases": [
            "brows",
            "eyebrow",
            "brow lamination",
            "brow tint",
            "brow shaping",
            "do you do brows",
            "eyebrow service",
            "brow service",
            "eyebrow lamination",
            "eyebrow tinting",
            "eyebrow shaping",
            "brow lami", "brow lam", "brow lammy", "brow lamination",
            "laminate brows", "lamination for brows", "lami for brows",
            "brow lift", "brow lift treatment", "brow lift and tint",
          
            "brow tint", "tint brows", "eyebrow tint", "brow shaping",
            "brow wax", "brow wax and tint", "brow cleanup",
            "shape my brows", "fix my brows", "clean up my brows",
         
            "brow combo", "brow package", "brow set", "brows package",
            "brows + tint", "brows and tint", "brows and lamination",
         
            "do u do brows", "do you guys do brows", "can you do my brows",
            "i need my brows done", "i wanna do my brows",
            "brow appointment", "book brows", "schedule brows",
            "how much for brows", "brow prices", "brow cost",
         
            "eyebrows", "eyebrowz", "browz", "lamenation", "laminaton",
            "tent brows", "brow tints",
            ],
        "message": {
            "en": [
                "🌸LIMITED TIME PROMO",
                "",
                "3-in-1 Brow Combo – only $110",
                "✨Shaping",
                "✨Lamination",
                "✨Tinting",
                "",
                "Plus complimentary aftercare gift 🎁",
                "",
                "Our product contains keratin to strengthen and protect your brows, promoting healthier growth.",
                "",
                "It's the perfect combo for fuller, fluffier, and more defined brows.",
            ],
            "es": [
                "🌸PROMO POR TIEMPO LIMITADO",
                "",
                "Combo de Cejas 3 en 1 – solo $110",
                "✨Diseño",
                "✨Laminación",
                "✨Tinte",
                "",
                "Más regalo de cuidado posterior de cortesía 🎁",
                "",
                "Nuestro producto contiene queratina para fortalecer y proteger tus cejas, promoviendo un crecimiento más saludable.",
                "",
                "Es el combo perfecto para cejas más llenas, más esponjosas y más definidas.",
            ],
        },
    },
    "face_laser": {
        "aliases": [
            "face laser",
            "laser face",
            "full face laser",
            "facial laser",
            "face hair removal",
            "laser for face",
            "full face laser", "laser full face", "laser on face", "laser for face",
            "face hair removal", "remove facial hair", "chin hair laser",
            "upper lip laser", "mustache laser", "sideburn laser", "cheeks laser",
            "jawline laser", "neck laser", "forehead laser",
            
            "razor bumps", "bumps from shaving", "ingrowns on face",
            "ingrown hairs on face", "shaving bumps",
            
            "laser my face", "can i do laser on my face", "do u do face laser",
            "how much for face laser", "face laser price", "face laser cost",
            
            "facelaser", "laserface", "laser for my fase",
        ],
        "message": {
            "en": [
                "✨LIMITED TIME PROMO",
                "",
                "Diode Laser Hair Removal",
                "Full Face – only $80",
                "",
                "✔ Reduces razor bumps",
                "✔ Helps with ingrown hairs",
                "✔ Safe for all skin & hair types",
                "",
                "✨SPECIAL BONUS:",
                "",
                "If you complete all 6 sessions consecutively you will keep the promo price.",
            ],
            "es": [
                "✨PROMO POR TIEMPO LIMITADO",
                "",
                "Depilación Láser Diodo",
                "Rostro Completo – solo $80",
                "",
                "✔ Reduce las protuberancias de la navaja",
                "✔ Ayuda con los vellos encarnados",
                "✔ Seguro para todos los tipos de piel y cabello",
                "",
                "✨BONO ESPECIAL:",
                "",
                "Si completas las 6 sesiones consecutivamente, mantendrás el precio promocional.",
            ],
        },
    },
    "lash_combo": {
        "aliases": [
            "lash",
            "lashes",
            "lash lamination",
            "lash tint",
            "lash tinting",
            "lash lamination and tint",
            "lash lamination + tint",
            "lash service",
            "lash treatment",
            "do you do lashes",
            "lash price",
            "lash booking",
            "can i get lashes",
            "i want lashes",
            "eyelash",
            "eyelashes",
            "eyelash lamination",
            "eyelash tinting",
            "lash lift", "lash lift and tint", "lash lift+tint", "lash lifting",
            "lash perm", "lash perm and tint",
           
            "lashes", "lash", "lash appointment", "book lashes", "schedule lashes",
            "i need my lashes done", "i wanna do lashes",
            "how much for lash lift", "lash lift price", "lash tint price",
           
            "lash lam", "lash lami", "lash laminaton", "lash lamnation",
            "tinting lashes", "lash tints",
        ],
        "message": {
            "en": [
                "🌸LIMITED TIME PROMO",
                "",
                "2-in-1 Lash Combo – only $90",
                "✨Lamination",
                "✨Tinting",
            ],
            "es": [
                "🌸PROMO POR TIEMPO LIMITADO",
                "",
                "Combo de Pestañas 2 en 1 – solo $90",
                "✨Laminación",
                "✨Tinte",
            ],
        },
    },
    "microdermabrasion": {
        "aliases": [
            "microdermabrasion",
            "microderm",
            "micro dermabrasion",
            "micro derm",
            "dermabrasion",
            "do you do microdermabrasion",
            "microdermabrasion treatment",
            "microdermabrasion price",
            "microdermabrasion service",
            "skin exfoliation",
            "exfoliation treatment",
            "microderm", "micro derm", "micro-derm", "micro derm treatment",
            "diamond facial", "diamond peel", "skin resurfacing",
            "texture facial", "rough skin", "skin polishing",
            "exfoliation facial", "deep exfoliation",
            "how much for microderm", "microderm price", "microderm cost",
        ],
        "message": {
            "en": [
               "💆🏼‍♀️ Microdermabrasion – $180",
               "",
               "A non-invasive exfoliation treatment designed to improve skin texture and stimulate healthy cell turnover.",
               "",
               "This treatment helps reduce the appearance of fine lines, uneven tone, superficial scarring, and enlarged pores, leaving the skin smoother, brighter, and more refreshed."
            ],
            "es": [
              "💆🏼‍♀️ Microdermoabrasión – $180",
              "",
              "Un tratamiento de exfoliación no invasivo diseñado para mejorar la textura de la piel y estimular una renovación celular saludable.",
              "",
              "Este tratamiento ayuda a reducir la apariencia de líneas finas, tono desigual, cicatrices superficiales y poros dilatados, dejando la piel más suave, luminosa y renovada."
            ],
        },
    },
    "facelift_massage": {
        "aliases": [
            "facelift massage",
            "face lift massage",
            "lifting facial massage",
            "face lifting massage",
            "sculpting facial massage",
            "facial sculpting massage",
            "lymphatic facial massage",
            "lymphatic drainage facial",
            "lymphatic drainage face massage",
            "sculpting massage face",
            "jawline sculpting massage",
            "lifting massage for face",
            "face sculpting",
            "facial lifting massage",
            "how much is facelift massage",
            "facelift massage price",
            "price for facelift massage",
            "book facelift massage",
            "facelift massage appointment",
        ],
        "message": {
            "en": [
              "💆‍♂️ Facelift Massage – $90",
              "",
              "A specialized facial massage focused on lifting, sculpting, and toning the facial muscles while promoting circulation and lymphatic drainage.",
              "",
              "This treatment helps reduce puffiness, soften fine lines, relieve facial tension, and support a more refreshed, youthful appearance."
            ],
            "es": [
              "💆‍♂️ Masaje Lifting Facial – $90",
              "",
              "Un masaje facial especializado enfocado en levantar, esculpir y tonificar los músculos del rostro, mientras promueve la circulación y el drenaje linfático.",
              "",
              "Este tratamiento ayuda a reducir la hinchazón, suavizar líneas finas, aliviar la tensión facial y favorecer una apariencia más fresca y juvenil."
            ],   
        },
    },
}

