from __future__ import annotations

from app.domain.entities.service_catalog import ServiceCatalogEntry

SERVICE_CATALOG: dict[str, ServiceCatalogEntry] = {
    "full body diode laser": ServiceCatalogEntry(
        service_key="full body diode laser",
        display_name="Full Body Diode Laser",
        category="Laser Hair Removal – Women",
        price_min=150,
        price_max=150,
        duration_minutes_min=60,
        duration_minutes_max=60,
        notes=None,
    ),
    "full face laser": ServiceCatalogEntry(
        service_key="full face laser",
        display_name="Full Face Laser (Add-on with Full Body only)",
        category="Laser Hair Removal – Women",
        price_min=50,
        price_max=50,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes="Add-on with Full Body only",
    ),
    "full legs": ServiceCatalogEntry(
        service_key="full legs",
        display_name="Full Legs",
        category="Laser Hair Removal – Women",
        price_min=60,
        price_max=60,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "lower legs": ServiceCatalogEntry(
        service_key="lower legs",
        display_name="Lower Legs",
        category="Laser Hair Removal – Women",
        price_min=35,
        price_max=35,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "full arms": ServiceCatalogEntry(
        service_key="full arms",
        display_name="Full Arms",
        category="Laser Hair Removal – Women",
        price_min=50,
        price_max=50,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "lower arms": ServiceCatalogEntry(
        service_key="lower arms",
        display_name="Lower Arms",
        category="Laser Hair Removal – Women",
        price_min=30,
        price_max=30,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "chest": ServiceCatalogEntry(
        service_key="chest",
        display_name="Chest",
        category="Laser Hair Removal – Women",
        price_min=30,
        price_max=30,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "abdomen": ServiceCatalogEntry(
        service_key="abdomen",
        display_name="Abdomen",
        category="Laser Hair Removal – Women",
        price_min=30,
        price_max=30,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "brazilian bikini": ServiceCatalogEntry(
        service_key="brazilian bikini",
        display_name="Brazilian (Bikini)",
        category="Laser Hair Removal – Women",
        price_min=65,
        price_max=65,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "back": ServiceCatalogEntry(
        service_key="back",
        display_name="Back",
        category="Laser Hair Removal – Women",
        price_min=45,
        price_max=45,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "underarms": ServiceCatalogEntry(
        service_key="underarms",
        display_name="Underarms",
        category="Laser Hair Removal – Women",
        price_min=45,
        price_max=45,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "upper lip": ServiceCatalogEntry(
        service_key="upper lip",
        display_name="Upper Lip",
        category="Face Laser – Women",
        price_min=30,
        price_max=30,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "forehead": ServiceCatalogEntry(
        service_key="forehead",
        display_name="Forehead",
        category="Face Laser – Women",
        price_min=40,
        price_max=40,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "sideburns cheeks": ServiceCatalogEntry(
        service_key="sideburns cheeks",
        display_name="Sideburns / Cheeks",
        category="Face Laser – Women",
        price_min=40,
        price_max=40,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "chin": ServiceCatalogEntry(
        service_key="chin",
        display_name="Chin",
        category="Face Laser – Women",
        price_min=30,
        price_max=30,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "neck": ServiceCatalogEntry(
        service_key="neck",
        display_name="Neck",
        category="Face Laser – Women",
        price_min=45,
        price_max=45,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "jawline": ServiceCatalogEntry(
        service_key="jawline",
        display_name="Jawline",
        category="Face Laser – Women",
        price_min=30,
        price_max=30,
        duration_minutes_min=15,
        duration_minutes_max=15,
        notes=None,
    ),
    "nose diode laser": ServiceCatalogEntry(
        service_key="nose diode laser",
        display_name="Nose (Diode Laser)",
        category="Face Laser – Women",
        price_min=40,
        price_max=40,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "full upper body diode laser men": ServiceCatalogEntry(
        service_key="full upper body diode laser men",
        display_name="Full Upper Body Diode Laser (Men)",
        category="Laser Hair Removal – Men",
        price_min=250,
        price_max=250,
        duration_minutes_min=60,
        duration_minutes_max=60,
        notes=None,
    ),
    "full face laser men": ServiceCatalogEntry(
        service_key="full face laser men",
        display_name="Full Face Laser (Men)",
        category="Laser Hair Removal – Men",
        price_min=80,
        price_max=80,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "upper body one part men": ServiceCatalogEntry(
        service_key="upper body one part men",
        display_name="Upper Body – One Part (Men)",
        category="Laser Hair Removal – Men",
        price_min=90,
        price_max=90,
        duration_minutes_min=30,
        duration_minutes_max=30,
        notes=None,
    ),
    "facial deep blackhead removal": ServiceCatalogEntry(
        service_key="facial deep blackhead removal",
        display_name="Facial + Deep Blackhead Removal",
        category="Facials & Skin",
        price_min=120,
        price_max=150,
        duration_minutes_min=60,
        duration_minutes_max=90,
        notes="Price varies depending on skin concerns and treatment needs",
    ),
    "facelift massage": ServiceCatalogEntry(
        service_key="facelift massage",
        display_name="Facelift Massage",
        category="Facials & Skin",
        price_min=90,
        price_max=90,
        duration_minutes_min=40,
        duration_minutes_max=40,
        notes=None,
    ),
    "microdermabrasion": ServiceCatalogEntry(
        service_key="microdermabrasion",
        display_name="Microdermabrasion",
        category="Facials & Skin",
        price_min=180,
        price_max=180,
        duration_minutes_min=120,
        duration_minutes_max=120,
        notes=None,
    ),
    "facial led light": ServiceCatalogEntry(
        service_key="facial led light",
        display_name="Facial + LED Light",
        category="Facials & Skin",
        price_min=170,
        price_max=170,
        duration_minutes_min=90,
        duration_minutes_max=90,
        notes=None,
    ),
    "facial masks": ServiceCatalogEntry(
        service_key="facial masks",
        display_name="Facial + Masks",
        category="Facials & Skin",
        price_min=160,
        price_max=160,
        duration_minutes_min=90,
        duration_minutes_max=90,
        notes=None,
    ),
    "lash lamination tinting": ServiceCatalogEntry(
        service_key="lash lamination tinting",
        display_name="Lash Lamination + Tinting",
        category="Lashes & Brows",
        price_min=90,
        price_max=90,
        duration_minutes_min=90,
        duration_minutes_max=90,
        notes=None,
    ),
    "lash lamination": ServiceCatalogEntry(
        service_key="lash lamination",
        display_name="Lash Lamination",
        category="Lashes & Brows",
        price_min=80,
        price_max=80,
        duration_minutes_min=60,
        duration_minutes_max=60,
        notes=None,
    ),
    "eyebrow lamination tint shaping": ServiceCatalogEntry(
        service_key="eyebrow lamination tint shaping",
        display_name="Eyebrow Lamination + Tint + Shaping",
        category="Lashes & Brows",
        price_min=110,
        price_max=110,
        duration_minutes_min=60,
        duration_minutes_max=90,
        notes=None,
    ),
    "eyebrow lamination": ServiceCatalogEntry(
        service_key="eyebrow lamination",
        display_name="Eyebrow Lamination",
        category="Lashes & Brows",
        price_min=85,
        price_max=85,
        duration_minutes_min=60,
        duration_minutes_max=60,
        notes=None,
    ),
    "eyebrow tinting": ServiceCatalogEntry(
        service_key="eyebrow tinting",
        display_name="Eyebrow Tinting",
        category="Lashes & Brows",
        price_min=85,
        price_max=85,
        duration_minutes_min=60,
        duration_minutes_max=60,
        notes=None,
    ),
    "eyebrow shaping": ServiceCatalogEntry(
        service_key="eyebrow shaping",
        display_name="Eyebrow Shaping",
        category="Lashes & Brows",
        price_min=85,
        price_max=85,
        duration_minutes_min=60,
        duration_minutes_max=60,
        notes=None,
    ),
    "pmu lips": ServiceCatalogEntry(
        service_key="pmu lips",
        display_name="PMU – Lips",
        category="Permanent Makeup (PMU)",
        price_min=300,
        price_max=300,
        duration_minutes_min=120,
        duration_minutes_max=150,
        notes=None,
    ),
    "pmu eyebrows": ServiceCatalogEntry(
        service_key="pmu eyebrows",
        display_name="PMU – Eyebrows",
        category="Permanent Makeup (PMU)",
        price_min=350,
        price_max=350,
        duration_minutes_min=120,
        duration_minutes_max=150,
        notes=None,
    ),
    "pmu eyeliner": ServiceCatalogEntry(
        service_key="pmu eyeliner",
        display_name="PMU – Eyeliner",
        category="Permanent Makeup (PMU)",
        price_min=250,
        price_max=250,
        duration_minutes_min=120,
        duration_minutes_max=150,
        notes=None,
    ),
    "lip pmu touch up": ServiceCatalogEntry(
        service_key="lip pmu touch up",
        display_name="Lip PMU Touch-up",
        category="Permanent Makeup (PMU)",
        price_min=200,
        price_max=200,
        duration_minutes_min=120,
        duration_minutes_max=120,
        notes=None,
    ),
    "eyebrow pmu touch up": ServiceCatalogEntry(
        service_key="eyebrow pmu touch up",
        display_name="Eyebrow PMU Touch-up",
        category="Permanent Makeup (PMU)",
        price_min=250,
        price_max=250,
        duration_minutes_min=120,
        duration_minutes_max=120,
        notes=None,
    ),
    "deposit hold": ServiceCatalogEntry(
        service_key="deposit hold",
        display_name="Deposit Hold",
        category="Other",
        price_min=20,
        price_max=20,
        duration_minutes_min=5,
        duration_minutes_max=5,
        notes=None,
    ),
}

